#
default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  host: localhost
  pool: <%= ENV["RAILS_DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
  port: <%= ENV['RAILS_DATABASE_PORT'] || 5432 %>


  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
development:
  <<: *default
  adapter: postgresql
  database: blog_7_dev

 
test:
  <<: *default
  adapter: postgresql
  database: blog_7_test